version: '3'

services:
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo_data:/data/db
    command: mongod --replSet rs0

volumes:
  mongo_data:
    driver: local
